<?php

namespace ContainerELxaT7V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScrapPageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.zb.J0RG.App\Entity\ScrapPage' shared service.
     *
     * @return \App\Entity\ScrapPage
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.zb.J0RG": it references class "App\\Entity\\ScrapPage" but no such service exists.');
    }
}
