<?php

namespace ContainerZLhxk5Q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Zb_J0RGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zb.J0RG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zb.J0RG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'scrap_page' => ['privates', '.errored..service_locator.zb.J0RG.App\\Entity\\ScrapPage', NULL, 'Cannot autowire service ".service_locator.zb.J0RG": it references class "App\\Entity\\ScrapPage" but no such service exists.'],
        ], [
            'scrap_page' => 'App\\Entity\\ScrapPage',
        ]);
    }
}
