<?php

namespace ContainerZLhxk5Q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScrapCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\ScrapCommand' shared autowired service.
     *
     * @return \App\Command\ScrapCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/ScrapCommand.php';

        $container->privates['App\\Command\\ScrapCommand'] = $instance = new \App\Command\ScrapCommand(($container->services['doctrine'] ?? $container->getDoctrineService()), ($container->services['kernel'] ?? $container->get('kernel', 1)));

        $instance->setName('scrap');
        $instance->setDescription('Add a short description for your command');

        return $instance;
    }
}
