<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerELxaT7V\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerELxaT7V/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerELxaT7V.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerELxaT7V\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerELxaT7V\App_KernelDevDebugContainer([
    'container.build_hash' => 'ELxaT7V',
    'container.build_id' => 'e6906816',
    'container.build_time' => 1670028047,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerELxaT7V');
